name: flutter_locker
description: Plugin that secures your secrets in keychain using biometric authentication.
version: 1.0.0
repository: https://github.com/infinum/flutter-plugins-locker

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  protobuf: ^1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_locker
        pluginClass: FlutterLockerPlugin
      ios:
        pluginClass: FlutterLockerPlugin
