name: flutter_locker
description: Secures your secrets in keychain using biometric authentication (Fingerprint, Touch ID, Face ID...)
version: 1.0.2
repository: https://github.com/infinum/flutter-plugins-locker
homepage: https://github.com/infinum/flutter-plugins-locker

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  protobuf: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_locker
        pluginClass: FlutterLockerPlugin
      ios:
        pluginClass: FlutterLockerPlugin
