name: flutter_locker
description: Secures your secrets in keychain using biometric authentication (Fingerprint, Touch ID, Face ID...)
version: 2.1.3
repository: https://github.com/infinum/flutter-plugins-locker
homepage: https://github.com/infinum/flutter-plugins-locker

environment:
  sdk: '>=2.16.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  pigeon: ^17.0.0
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_locker
        pluginClass: FlutterLockerPlugin
      ios:
        pluginClass: FlutterLockerPlugin
